### ISSUE TITLE
Reporte de Practica8

### ISSUE THREAD

**Issue by williamgl3** [SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-equipo-topicos-as#2]
https://drive.google.com/file/d/1AsAnGerTvJqSK-rnCQgIEkHp_PmRe35c/view?usp=sharing

**Comment by ArcangelGC** [comment]
Recibi practica 8. ✍🏼
En base a la rubrica se le hacen las siguientes observaciones o sugerencias.

- Falto una tabla de imagenes para que cumpliera con todas las especificaciones de la rubrica.
- Lo demás estas bien.

Calificacion: 19/20

**Comment by josealfredo79** [comment]
Bien hecho y recibido...
